"""add salary_calculations table

Revision ID: 440cdc38fc4d
Revises: b6a8e17c8717
Create Date: 2026-07-17 21:10:47.478338
"""
from alembic import op
import sqlalchemy as sa


revision = '440cdc38fc4d'
down_revision = 'b6a8e17c8717'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_calculations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('monthly_salary', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('performance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('subsidies', sa.JSON(), nullable=True),
    sa.Column('housing_ratio', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('supplementary_housing_ratio', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('supplementary_medical', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('special_deduction', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('social_insurance_base', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bonus_months', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('living_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('result_take_home', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('result_annual_take_home', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('result_savings_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salary_calculations')
    # ### end Alembic commands ###
