"""add is_admin to users

Revision ID: 61644e47fec4
Revises: 440cdc38fc4d
Create Date: 2026-07-17 22:17:31.710778
"""
from alembic import op
import sqlalchemy as sa


revision = '61644e47fec4'
down_revision = '440cdc38fc4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
