"""add review_rules table

Revision ID: a31f5740d0c5
Revises: 61644e47fec4
Create Date: 2026-07-17 22:33:36.539326
"""
from alembic import op
import sqlalchemy as sa


revision = 'a31f5740d0c5'
down_revision = '61644e47fec4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('risk_type', sa.String(length=100), nullable=False),
    sa.Column('condition_type', sa.String(length=32), nullable=False),
    sa.Column('condition_value', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('suggestion', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_rules_condition_type'), 'review_rules', ['condition_type'], unique=False)
    op.create_index(op.f('ix_review_rules_priority'), 'review_rules', ['priority'], unique=False)
    op.create_index(op.f('ix_review_rules_risk_level'), 'review_rules', ['risk_level'], unique=False)
    op.create_index(op.f('ix_review_rules_rule_code'), 'review_rules', ['rule_code'], unique=True)
    # ### end Alembic commands ###

    # 种子数据：将内置规则迁移到数据库
    review_rules = sa.table(
        'review_rules',
        sa.column('name', sa.String),
        sa.column('rule_code', sa.String),
        sa.column('risk_type', sa.String),
        sa.column('condition_type', sa.String),
        sa.column('condition_value', sa.Text),
        sa.column('risk_level', sa.String),
        sa.column('suggestion', sa.Text),
        sa.column('priority', sa.Integer),
        sa.column('is_active', sa.Boolean),
        sa.column('is_deleted', sa.Boolean),
    )
    op.bulk_insert(review_rules, [
        {"name": "试用期可能偏长", "rule_code": "probation_too_long", "risk_type": "试用期长度需要和合同期限匹配。合同1年以下试用期不超过1个月，1-3年不超过2个月，3年以上不超过6个月。", "condition_type": "contains_any", "condition_value": '["试用期六个月","试用期6个月","试用期三个月","试用期3个月"]', "risk_level": "medium", "suggestion": "确认合同期限和试用期的对应关系是否合法", "priority": 10, "is_active": True, "is_deleted": False},
        {"name": "试用期工资比例需确认", "rule_code": "probation_salary_low", "risk_type": "法律规定试用期工资不得低于转正工资的80%。", "condition_type": "contains_any", "condition_value": '["试用期工资","试用期薪酬"]', "risk_level": "medium", "suggestion": "确认试用期工资是否不低于转正工资的80%", "priority": 20, "is_active": True, "is_deleted": False},
        {"name": "有竞业限制但未见补偿约定", "rule_code": "non_compete_no_compensation", "risk_type": "竞业限制期间公司必须按月给予经济补偿，否则条款可能无效。", "condition_type": "contains_any", "condition_value": '["竞业限制","竞业禁止","竞业条款"]', "risk_level": "high", "suggestion": "这一条签之前一定要问清楚：竞业限制的补偿金是多少、按月还是按年支付", "priority": 30, "is_active": True, "is_deleted": False},
        {"name": "违约金条款需注意", "rule_code": "penalty_on_employee", "risk_type": "法律规定只有两种情况可以约定由劳动者承担违约金：培训服务期和竞业限制。其他情况的违约金条款可能无效。", "condition_type": "contains_any", "condition_value": '["违约金","赔偿金","违反本合同"]', "risk_level": "high", "suggestion": "确认违约金是否仅限于培训服务期或竞业限制两种情形", "priority": 40, "is_active": True, "is_deleted": False},
        {"name": "工作地点表述模糊", "rule_code": "work_location_vague", "risk_type": "工作地点不明确可能导致后续被跨城市调动。", "condition_type": "contains_any", "condition_value": '["根据经营需要","公司安排","甲方指定","根据需要调整"]', "risk_level": "medium", "suggestion": "确认工作地点是否固定到具体城市，是否有跨城调动的可能", "priority": 50, "is_active": True, "is_deleted": False},
        {"name": "合同解除权偏单方", "rule_code": "termination_unilateral", "risk_type": "如果合同只规定了公司可以单方解除，但没有对等的劳动者解除权说明，需要注意。", "condition_type": "contains_any", "condition_value": '["甲方有权解除","公司有权解除","单方解除","随时解除"]', "risk_level": "high", "suggestion": "确认解除条件是否对等，劳动者提前30天书面通知即可解除", "priority": 60, "is_active": True, "is_deleted": False},
        {"name": "社保条款未明确", "rule_code": "social_insurance_missing", "risk_type": "缴纳社保是法定义务，任何放弃社保的约定都是无效的。", "condition_type": "contains_any", "condition_value": '["不缴纳社保","自愿放弃社保","社保补贴"]', "risk_level": "high", "suggestion": "这一条签之前一定要问清楚：社保是否按实际工资基数缴纳", "priority": 70, "is_active": True, "is_deleted": False},
        {"name": "加班补偿条款需确认", "rule_code": "overtime_no_compensation", "risk_type": "加班应当支付加班费或安排调休。", "condition_type": "contains_any", "condition_value": '["无条件加班","自愿加班","不计算加班费","弹性工时不含加班"]', "risk_level": "medium", "suggestion": "确认加班是否有补偿机制（加班费或调休）", "priority": 80, "is_active": True, "is_deleted": False},
    ])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_rules_rule_code'), table_name='review_rules')
    op.drop_index(op.f('ix_review_rules_risk_level'), table_name='review_rules')
    op.drop_index(op.f('ix_review_rules_priority'), table_name='review_rules')
    op.drop_index(op.f('ix_review_rules_condition_type'), table_name='review_rules')
    op.drop_table('review_rules')
    # ### end Alembic commands ###
