"""add offer name field and salary_calculations table

Revision ID: b6a8e17c8717
Revises: 0001
Create Date: 2026-07-17 17:21:01.732608
"""
from alembic import op
import sqlalchemy as sa


revision = 'b6a8e17c8717'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'name')
    # ### end Alembic commands ###
