version: 2
updates:
  - package-ecosystem: npm
    directory: /zhihu/zhihu-frontend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: pip
    directory: /zhihu/zhihu-backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

