export interface SenseAudioVoiceOption {
  id: string;
  label: string;
}

export const SENSEAUDIO_TTS_VOICES: SenseAudioVoiceOption[] = [
  { id: "female_0038_b", label: "亲切女孩 · 温柔讲解（推荐）" },
  { id: "female_0038_a", label: "亲切女孩 · 平稳通用" },
  { id: "female_0038_c", label: "亲切女孩 · 致歉安慰" },
  { id: "female_0038_d", label: "亲切女孩 · 严肃告知" },
  { id: "female_0038_e", label: "亲切女孩 · 清晰播报" },
  { id: "female_0038_f", label: "亲切女孩 · 耐心关怀" },
  { id: "female_0037_a", label: "自然少女 · 劝导" },
  { id: "female_0037_b", label: "自然少女 · 委屈" },
  { id: "female_0037_c", label: "自然少女 · 温柔" },
  { id: "female_0037_d", label: "自然少女 · 严肃" },
  { id: "female_0037_e", label: "自然少女 · 平稳" },
  { id: "female_0036_a", label: "青春女声 · 内容剖析" },
  { id: "female_0036_b", label: "青春女声 · 开场介绍" },
  { id: "female_0036_c", label: "青春女声 · 广告中插" },
  { id: "female_0036_d", label: "青春女声 · 轻松铺陈" },
  { id: "female_0036_e", label: "青春女声 · 细心提问" },
  { id: "female_0036_f", label: "青春女声 · 主题升华" },
  { id: "male_0029_a", label: "利落青年 · 内容剖析" },
  { id: "male_0029_b", label: "利落青年 · 开场介绍" },
  { id: "male_0029_c", label: "利落青年 · 广告中插" },
  { id: "male_0029_d", label: "利落青年 · 轻松铺陈" },
  { id: "male_0029_e", label: "利落青年 · 细心提问" },
  { id: "male_0029_f", label: "利落青年 · 主题升华" },
  { id: "female_0035_a", label: "知心少女 · 内容剖析" },
  { id: "female_0035_b", label: "知心少女 · 开场介绍" },
  { id: "female_0035_c", label: "知心少女 · 广告中插" },
  { id: "female_0035_d", label: "知心少女 · 轻松铺陈" },
  { id: "female_0035_e", label: "知心少女 · 细心提问" },
  { id: "female_0035_f", label: "知心少女 · 主题升华" },
  { id: "male_0028_a", label: "可靠青叔 · 内容剖析" },
  { id: "male_0028_b", label: "可靠青叔 · 开场介绍" },
  { id: "male_0028_c", label: "可靠青叔 · 广告中插" },
  { id: "male_0028_d", label: "可靠青叔 · 轻松铺陈" },
  { id: "male_0028_e", label: "可靠青叔 · 细心提问" },
  { id: "male_0028_f", label: "可靠青叔 · 主题升华" },
  { id: "female_0008_c", label: "气质学姐 · 平稳" },
  { id: "female_0008_b", label: "气质学姐 · 开心" },
  { id: "female_0008_a", label: "气质学姐 · 生气" },
  { id: "female_0016_a", label: "俏皮女孩 · 开心" },
  { id: "female_0016_b", label: "俏皮女孩 · 低落" },
  { id: "female_0016_c", label: "俏皮女孩 · 傲娇" },
  { id: "male_0025_a", label: "温柔霸总 · 平稳" },
  { id: "male_0025_b", label: "温柔霸总 · 严肃" },
  { id: "male_0025_c", label: "温柔霸总 · 深情" },
  { id: "male_0017_a", label: "温柔青年 · 平稳" },
  { id: "female_0030_b", label: "沉稳帅姐 · 平稳" },
  { id: "male_0022_a", label: "阳光少年 · 平稳" },
  { id: "female_0030_e", label: "贴心女人 · 深情" },
  { id: "female_0018_a", label: "森系少女 · 害羞" },
  { id: "female_0018_b", label: "森系少女 · 开心" },
  { id: "female_0004_a", label: "乐天女孩 · 开心" },
  { id: "female_0019_a", label: "冷艳御姐 · 平稳" },
  { id: "female_0023_a", label: "羞涩甜妹 · 平稳" },
  { id: "female_0023_b", label: "羞涩甜妹 · 开心" },
  { id: "female_0023_c", label: "羞涩甜妹 · 傲娇" },
  { id: "female_0030_a", label: "凌厉御姐 · 平稳" },
  { id: "female_0030_c", label: "高能姐姐 · 平稳" },
  { id: "child_0001_b", label: "可爱萌娃 · 平稳" },
  { id: "child_0001_a", label: "可爱萌娃 · 开心" },
  { id: "male_0004_a", label: "儒雅道长 · 平稳" },
  { id: "male_0018_a", label: "沙哑青年 · 深情" },
  { id: "male_0027_a", label: "亢奋主播 · 热情介绍" },
  { id: "male_0027_b", label: "亢奋主播 · 卖点解读" },
  { id: "male_0027_c", label: "亢奋主播 · 促销逼单" },
  { id: "male_0023_a", label: "撒娇青年 · 平稳" },
  { id: "male_0019_a", label: "孔武青年 · 平稳" },
  { id: "female_0033_a", label: "嗲嗲台妹 · 平稳" },
  { id: "female_0033_b", label: "嗲嗲台妹 · 开心" },
  { id: "female_0033_c", label: "嗲嗲台妹 · 撒娇" },
  { id: "female_0033_d", label: "嗲嗲台妹 · 低落" },
  { id: "female_0033_e", label: "嗲嗲台妹 · 委屈" },
  { id: "female_0033_f", label: "嗲嗲台妹 · 生气" },
  { id: "male_0026_a", label: "乐观少年 · 平稳" },
  { id: "male_0026_b", label: "乐观少年 · 开心" },
  { id: "male_0026_c", label: "乐观少年 · 深情" },
  { id: "female_0006_a", label: "温柔御姐 · 深情" },
  { id: "female_0027_a", label: "魅力姐姐 · 平稳" },
  { id: "female_0027_b", label: "魅力姐姐 · 撒娇" },
  { id: "female_0027_c", label: "魅力姐姐 · 病娇" },
  { id: "female_0027_d", label: "魅力姐姐 · 低落" },
  { id: "female_0027_e", label: "魅力姐姐 · 妩媚" },
  { id: "female_0027_f", label: "魅力姐姐 · 傲娇" },
];

export const SENSEAUDIO_REALTIME_VOICES: SenseAudioVoiceOption[] = [
  { id: "f_y_0035_c", label: "清风少女 · 平稳（推荐）" },
  { id: "f_y_0035_a", label: "清风少女 · 傲娇" },
  { id: "f_y_0039_c", label: "知心少女 · 广告中插" },
  { id: "f_y_0039_d", label: "知心少女 · 轻松铺陈" },
  { id: "f_y_0037_f", label: "青春女声 · 主题升华" },
  { id: "f_y_0041_c", label: "亲切女孩 · 致歉安慰" },
  { id: "m_y_0022", label: "沙哑青年 · 深情" },
  { id: "m_y_0021", label: "撒娇青年 · 平稳" },
  { id: "m_y_0027", label: "粘人男友 · 平稳" },
  { id: "m_y_0027_a", label: "粘人男友 · 深情" },
  { id: "m_y_0028", label: "温柔霸总 · 平稳" },
  { id: "m_y_0034_d", label: "可靠青叔 · 细心提问" },
  { id: "m_y_0034_e", label: "可靠青叔 · 主题升华" },
  { id: "m_y_0036_e", label: "利落青年 · 细心提问" },
  { id: "m_c_0001", label: "可爱萌娃 · 开心" },
  { id: "5min_f_y_0003", label: "天真少女 · 平稳" },
  { id: "f_m_0006", label: "温柔御姐 · 深情" },
];

export function voiceOptionsWithCurrent(options: SenseAudioVoiceOption[], current: string) {
  return current && !options.some((option) => option.id === current)
    ? [{ id: current, label: `当前配置 · ${current}` }, ...options]
    : options;
}
